version: '3.5'

services:
  postgres:
    container_name: postgrescontainer
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres321
      POSTGRES_DB: playlist
    ports:
      - "5432:5432"
    networks:
      - crud
    restart: unless-stopped
  web:
    depends_on:
      - postgres
    container_name: musiccrud
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/playlist
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres321
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    networks:
      - crud
    restart: unless-stopped
networks:
  crud:
    driver: bridge